services:
  db:
    image: mysql:8.0.29
    container_name: mysql-server
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./sql/conf.d:/etc/mysql/conf.d:cached
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  app:
    build:
      context: .
    container_name: go-backend
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DB_USER: user
      DB_PASSWORD: password
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: mydb
    volumes:
      - ./uploads:/app/uploads

volumes:
  db_data:
